#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'nova-milestone-tarball',
 'build_date': '2011-09-22 12:02:27 +0000',
 'clean': None,
 'date': '2011-09-22 11:57:02 +0000',
 'revision_id': 'tarmac-20110922115702-k9nkvxqzhj130av2',
 'revno': 1201}

revisions = {}

file_revisions = {}


if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
